
server:
  port: 8888
  shutdown: graceful
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: config-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cvdejan/config-repo
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
#          basedir: /Users/dejan/Documents/code/backend/CloudNative/config-repo
logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

info:
  system: Polar Bookshop

management:
  endpoints:
    web:
      exposure:
        include: bindings, configprops, env, flyway, functions, health, heapdump, info, loggers, mappings, prometheus
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}